apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mgmds
spec:
  serviceName: "mgmd"
  replicas: 1
  selector:
    # Used by the Deployment to select and manage existing pods with the specified label
    matchLabels:
      app: mgmd
  template:
    metadata:
      # Used to apply labels to all pods created by the Deployment
      labels:
        app: mgmd
    spec:
      containers:
      - name: mgmd
        image: hopsworks/rondb-standalone:22.10.1
        args:
          - ndb_mgmd
          - --ndb-nodeid=65
          - --initial
        ports:
          - containerPort: 1186
        env:
          - name: HOST_GROUP_ID
            value: "0"
          # TODO: Parse ordinal number to apply for node-id
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
        # Only mount single file, otherwise entire directory becomes read-only
        - name: rondb-configs
          mountPath: /srv/hops/mysql-cluster/config.ini
          subPath: config.ini
        - name: rondb-mgmd-data
          mountPath: /srv/hops/mysql-cluster/data
        - name: rondb-mgmd-log
          mountPath: /srv/hops/mysql-cluster/log
      volumes:
      - name: rondb-configs
        configMap:
          name: rondb-configs
      - name: rondb-mgmd-data
        persistentVolumeClaim:
          claimName: rondb-mgmd-data-claim
      - name: rondb-mgmd-log
        persistentVolumeClaim:
          claimName: rondb-mgmd-log-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mgmd
spec:
  # Headless service for individual DNS records for the pods
  clusterIP: None
  # Match the spec.template.metadata.labels of the Deployment
  selector:
    app: mgmd
  ports:
    - protocol: TCP
      port: 1186
      targetPort: 1186
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rondb-mgmd-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rondb-mgmd-log-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
