dockerTag: 22.10.1

mysqlRootPassword: "Abc123?eeee"

benchmarking:
  enabled: false
  mysqlUsername: "hopsworks"
  mysqlPassword: "Abc123?e"
  type: "sysbench_single"
  dbt2:
    numWarehouses: 4
    runSingle: |
      # NUM_MYSQL_SERVERS  NUM_WAREHOUSES  NUM_TERMINALS
      1                    1               1
      1                    2               1
      1                    4               1
      1                    4               2
    runMulti: |
      # NUM_MYSQL_SERVERS  NUM_WAREHOUSES  NUM_TERMINALS
      2                    1               1
      2                    2               1
      2                    2               2
  sysbench:
    threadCountsToRun: "1;2;4;8;12;16;24;32"
    rows: 100000


clusterSize:
  activeDataReplicas: 1
  numNodeGroups: 1
  numMySQLServers: 2
  maxNumMySQLServers: 5
  numRdrs: 1
  maxNumRdrs: 2

configIni:
  NumCPUs: 4
  # The containers will otherwise assume that
  # they can occupy the entire node's memory
  # (at least in minikube + Docker driver)
  TotalMemoryConfig: 3100M
  MaxNoOfTables: 384
  MaxNoOfAttributes: 8000
  MaxNoOfTriggers: 4000
  TransactionMemory: 300M
  SharedGlobalMemory: 300M
  ReservedConcurrentOperations: 50000
  FragmentLogFileSize: 128M
  MaxNoOfConcurrentOperations: 200000

  MySQLdSlotsPerNode: 4
  RdrsSlotsPerNode: 2

resources:
  limits:
    cpus:
      mgmds: '0.2'
      ndbmtds: 2
      mysqlds: 2
      rdrs: 2
      benchs: 2
    memory:
      mgmds: 50M
      ndbmtds: 3300M
      mysqlds: 1400M
      rdrs: 500M
      benchs: 500M
  requests:
    cpus:
      mgmds: '0.2'
      ndbmtds: 1
      mysqlds: 1
      rdrs: 1
      benchs: 1
    memory:
      mgmds: 20M
      ndbmtds: 2300M
      mysqlds: 650M
      rdrs: 100M
      benchs: 100M
