{{- range $nodeGroup := until ($.Values.clusterSize.numNodeGroups | int) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  # This will have the form of "node-group-0-0", "node-group-0-1", etc.
  name: node-group-{{ $nodeGroup }}
spec:
  serviceName: ndbmtd-ng-{{ $nodeGroup }}
  replicas: {{ $.Values.clusterSize.activeDataReplicas }}
  selector:
    # Used by the Deployment to select and manage existing pods with the specified label
    matchLabels:
      rondbService: ndbmtd
      nodeGroup: "{{ $nodeGroup }}"
  template:
    metadata:
      # Used to apply labels to all pods created by the StatefulSet
      labels:
        rondbService: ndbmtd
        nodeGroup: "{{ $nodeGroup }}"
    spec:
      initContainers:
      - name: mgmd-dependency-check
        image: hopsworks/rondb-standalone:{{ $.Values.dockerTag }}
        command:
        - /bin/bash
        - -c
        - |
          until nslookup mgmds-0.mgmd.default.svc.cluster.local; do
            echo "Waiting for mgmds-0.mgmd.default.svc.cluster.local to be resolvable..."
            sleep $(((RANDOM % 2)+2))
          done
      containers:
      - name: ndbmtd
        image: hopsworks/rondb-standalone:{{ $.Values.dockerTag }}
        command: ["/srv/hops/docker/rondb_standalone/entrypoints/pre_entrypoint_k8.sh"]
        args:
          - ndbmtd
          - --initial
          - --ndb-connectstring=mgmds-0.mgmd.default.svc.cluster.local:1186
        ports:
          - containerPort: 11860
        resources:
          limits:
            cpu: {{ $.Values.resources.limits.cpus.ndbmtds }}
            memory: {{ $.Values.resources.limits.memory.ndbmtds }}
          requests:
            cpu: {{ $.Values.resources.requests.cpus.ndbmtds }}
            memory: {{ $.Values.resources.requests.memory.ndbmtds }}
        env:
          - name: HOST_GROUP_ID
            value: "0"
          - name: NODE_GROUP
            value: "{{ $nodeGroup }}"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - |
                # Equivalent to replication factor of pod
                POD_ID=$(echo $POD_NAME | grep -o '[0-9]\+$')
                NODE_ID_OFFSET=$(($NODE_GROUP*3))
                NODE_ID=$(($NODE_ID_OFFSET+$POD_ID+1))
                ./docker/rondb_standalone/healthcheck.sh mgmds-0.mgmd.default.svc.cluster.local:1186 $NODE_ID
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 15
          timeoutSeconds: 15
        volumeMounts:
        - name: rondb-ndbmtd-data
          mountPath: /srv/hops/mysql-cluster/ndb_data
        - name: rondb-ndbmtd-log
          mountPath: /srv/hops/mysql-cluster/log
      # StatefulSets work with PVCs to create a dedicated persistent volume for
      # each pod replica, ensuring that a pod always re-attaches to the same data
      # even if it is rescheduled to a different node.
      volumes:
      - name: rondb-ndbmtd-data
        persistentVolumeClaim:
          claimName: rondb-ndbmtd-data-claim
      - name: rondb-ndbmtd-log
        persistentVolumeClaim:
          claimName: rondb-ndbmtd-log-claim
---
apiVersion: v1
kind: Service
metadata:
  # Match the spec.serviceName
  name: ndbmtd-ng-{{ $nodeGroup }}
spec:
  # Headless service for individual DNS records for the pods
  clusterIP: None
  # Match the spec.template.metadata.labels of the StatefulSet
  selector:
    rondbService: ndbmtd
    nodeGroup: "{{ $nodeGroup }}"
  ports:
    - protocol: TCP
      port: 11860
      targetPort: 11860
---
{{ end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rondb-ndbmtd-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rondb-ndbmtd-log-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
