version: '3.7'

services:
  flask-server:
    image: hopsworks/flask-server-rondb:latest
    container_name: flask-server
    command: ["--no-active-test-worker"]
    environment:
      IMAGE_TO_SPAWN: hopsworks/rondb-managed:21.04.15-1.0
      CLOUD_BASE_URL: "http://flask-server:8000"
    ports:
      # Host:Docker
      - 8000:8000
    volumes:
      # This is to mount the desired_state.jsonc file. We're binding the
      # entire directory, since some editors (e.g. Vim) can overwrite the
      # file's inode when saving the file on host and thereby break the mount.
      - type: bind
        source: .
        target: /home/desired_state
      - type: bind
        source:  /var/run/docker.sock
        target:  /var/run/docker.sock

  # Host ndb-agent & RonDB tarballs for up/downgrades
  nginx:
    image: hopsworks/nginx-rondb:latest
    container_name: nginx
    restart: "no"
    expose:
      - 80

  # This container can be killed once the cluster is running
  bootstrap_agent:
    image: hopsworks/rondb-managed:21.04.15-1.0
    container_name: bootstrap_agent
    environment:
      IS_BOOTSTRAP_HOST: "true"
      CLOUD_BASE_URL: "http://flask-server:8000"
    volumes:
     - type: volume
       source: dummy_sink
       target: /home/sink

volumes:
  dummy_sink:


networks:
  default:
    attachable: true
